#!/bin/bash


echo "Compiling for Linux 64 ..."
GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -o netinfo" main.go 2>/dev/null
cp netinfo binaries/linux_x86_64/
rm netinfo

echo "Compiling for Linux 32 ..."
GOOS=linux GOARCH=386 go build -ldflags="-s -w -o netinfo" main.go 2>/dev/null
cp netinfo binaries/linux_x86_32/
rm netinfo

echo "Compiling for Mac OSX 64 ..."
GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -o netinfo" main.go 2>/dev/null
cp netinfo binaries/macosx_x86_64/
rm netinfo

echo "Compiling for raspberry pi v4 ..."
GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w -o netinfo" main.go 2>/dev/null
cp netinfo binaries/raspberry_pi_v4/
rm netinfo

echo "Compiling for Windows 64 ..."
GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -o netinfo.exe" main.go 2>/dev/null
cp netinfo.exe binaries/windows_x86_64/
rm netinfo.exe

exit 0
